### ISSUE TITLE
Newsletter Subscription - Connect to their MailChimp account.

### ISSUE THREAD

**Issue by tgascoigne14** [CCI-Studios/Community-Living-Sarnia#26]
Username and Password on Trello Card

**Comment by tgascoigne14** [comment]
Username: scolameco

Pass: Scolameco@1

**Comment by ccmorris** [comment]
@tgascoigne14 is there a list they want this to go into?

**Comment by ccmorris** [comment]
There is a bunch of lists in the account. Perhaps this one?

> Community Living Sarnia-Lambton Contacts

**Comment by tgascoigne14** [comment]
@ccmorris Indeed - please add to the Community Living Sarnia-Lambton Contacts list
